import { collection, addDoc, serverTimestamp, getDocs, query } from 'firebase/firestore'
import { db } from '../config/firebase'
import type { FirebaseEmployee } from '../hooks/useFirebaseEmployees'

const DUMMY_EMPLOYEES: Omit<FirebaseEmployee, 'id'>[] = [
  {
    name: 'Ahmed Raza',
    email: 'ahmed.raza@cabcallexperts.com',
    phone: '+44 7700 900001',
    dob: '1990-03-15',
    gender: 'Male',
    cnic: '35202-1234567-1',
    maritalStatus: 'Married',
    currentAddress: '12 Baker Street, Manchester, M1 2AB',
    employeeId: 'CCE001',
    jobTitle: 'Operations Manager',
    department: 'Operations',
    employmentType: 'full_time',
    status: 'active',
    startDate: '2021-01-10',
    workLocation: 'Head Office',
    manager: 'Sarah Thompson',
    salary: 38000,
    permanentAddress: '12 Baker Street, Manchester, M1 2AB',
    emergencyContactName: 'Fatima Raza',
    emergencyContactPhone: '+44 7700 900099',
    emergencyContactRelation: 'Spouse',
    bankName: 'Barclays',
    accountNumber: 'GB29BARC20000000000000',
    taxNumber: '12345678',
    skills: 'Operations Management, Team Leadership, Scheduling',
    notes: 'Top performer. Team lead for night shifts.',
  },
  {
    name: 'Sarah Thompson',
    email: 'sarah.thompson@cabcallexperts.com',
    phone: '+44 7700 900002',
    dob: '1985-07-22',
    gender: 'Female',
    cnic: '',
    maritalStatus: 'Single',
    currentAddress: '45 Oxford Road, Manchester, M13 9PL',
    employeeId: 'CCE002',
    jobTitle: 'HR Manager',
    department: 'Admin',
    employmentType: 'full_time',
    status: 'active',
    startDate: '2019-06-01',
    workLocation: 'Head Office',
    manager: 'CEO',
    salary: 42000,
    permanentAddress: '45 Oxford Road, Manchester, M13 9PL',
    emergencyContactName: 'John Thompson',
    emergencyContactPhone: '+44 7700 900098',
    emergencyContactRelation: 'Parent',
    bankName: 'HSBC',
    accountNumber: 'GB29HSBC20000000000001',
    taxNumber: '87654321',
    skills: 'HR Management, Recruitment, Payroll, Employment Law',
    notes: 'Senior HR lead. Handles compliance.',
  },
  {
    name: 'Usman Khan',
    email: 'usman.khan@cabcallexperts.com',
    phone: '+44 7700 900003',
    dob: '1994-11-05',
    gender: 'Male',
    cnic: '35201-9876543-1',
    maritalStatus: 'Single',
    currentAddress: '8 Deansgate, Manchester, M3 4LX',
    employeeId: 'CCE003',
    jobTitle: 'Dispatch Coordinator',
    department: 'Dispatch',
    employmentType: 'full_time',
    status: 'active',
    startDate: '2022-03-14',
    workLocation: 'Head Office',
    manager: 'Ahmed Raza',
    salary: 26000,
    emergencyContactName: 'Ali Khan',
    emergencyContactPhone: '+44 7700 900097',
    emergencyContactRelation: 'Parent',
    bankName: 'Lloyds',
    accountNumber: 'GB29LOYD20000000000002',
    taxNumber: '11223344',
    skills: 'Dispatch, Route Planning, Driver Communication',
  },
  {
    name: 'Zara Malik',
    email: 'zara.malik@cabcallexperts.com',
    phone: '+44 7700 900004',
    dob: '1997-02-28',
    gender: 'Female',
    cnic: '35202-7654321-2',
    maritalStatus: 'Single',
    currentAddress: '22 Princess Street, Manchester, M1 4LG',
    employeeId: 'CCE004',
    jobTitle: 'Customer Service Agent',
    department: 'Customer Service',
    employmentType: 'full_time',
    status: 'active',
    startDate: '2023-01-09',
    workLocation: 'Head Office',
    manager: 'Sarah Thompson',
    salary: 23000,
    emergencyContactName: 'Hina Malik',
    emergencyContactPhone: '+44 7700 900096',
    emergencyContactRelation: 'Sibling',
    bankName: 'NatWest',
    accountNumber: 'GB29NWBK20000000000003',
    skills: 'Customer Service, CRM, Complaint Handling',
  },
  {
    name: 'Daniel Okafor',
    email: 'daniel.okafor@cabcallexperts.com',
    phone: '+44 7700 900005',
    dob: '1991-09-14',
    gender: 'Male',
    maritalStatus: 'Married',
    currentAddress: '5 Piccadilly Gardens, Manchester, M1 1RG',
    employeeId: 'CCE005',
    jobTitle: 'IT Administrator',
    department: 'IT',
    employmentType: 'full_time',
    status: 'active',
    startDate: '2020-08-17',
    workLocation: 'Head Office',
    manager: 'Sarah Thompson',
    salary: 35000,
    emergencyContactName: 'Ngozi Okafor',
    emergencyContactPhone: '+44 7700 900095',
    emergencyContactRelation: 'Spouse',
    bankName: 'Barclays',
    accountNumber: 'GB29BARC20000000000004',
    taxNumber: '55667788',
    skills: 'Network Admin, Windows Server, Azure, Helpdesk',
    notes: 'Manages all hardware and software infrastructure.',
  },
  {
    name: 'Priya Sharma',
    email: 'priya.sharma@cabcallexperts.com',
    phone: '+44 7700 900006',
    dob: '1993-05-30',
    gender: 'Female',
    maritalStatus: 'Single',
    currentAddress: '19 Portland Street, Manchester, M1 3HT',
    employeeId: 'CCE006',
    jobTitle: 'Customer Service Team Lead',
    department: 'Customer Service',
    employmentType: 'full_time',
    status: 'on_leave',
    startDate: '2021-11-22',
    workLocation: 'Head Office',
    manager: 'Sarah Thompson',
    salary: 29000,
    emergencyContactName: 'Raj Sharma',
    emergencyContactPhone: '+44 7700 900094',
    emergencyContactRelation: 'Parent',
    bankName: 'HSBC',
    accountNumber: 'GB29HSBC20000000000005',
    skills: 'Team Management, Customer Relations, Quality Assurance',
    notes: 'Currently on maternity leave. Expected return: 2026-07-01.',
  },
  {
    name: 'James Mitchell',
    email: 'james.mitchell@cabcallexperts.com',
    phone: '+44 7700 900007',
    dob: '1988-12-01',
    gender: 'Male',
    maritalStatus: 'Divorced',
    currentAddress: '3 Albert Square, Manchester, M2 5PF',
    employeeId: 'CCE007',
    jobTitle: 'Senior Dispatcher',
    department: 'Dispatch',
    employmentType: 'full_time',
    status: 'active',
    startDate: '2018-04-03',
    workLocation: 'Head Office',
    manager: 'Ahmed Raza',
    salary: 30000,
    bankName: 'Lloyds',
    accountNumber: 'GB29LOYD20000000000006',
    taxNumber: '99887766',
    skills: 'Fleet Dispatch, GPS Tracking, Driver Management, Scheduling',
    notes: 'Most experienced dispatcher. Handles peak hours.',
  },
  {
    name: 'Aisha Siddiqui',
    email: 'aisha.siddiqui@cabcallexperts.com',
    phone: '+44 7700 900008',
    dob: '1996-08-18',
    gender: 'Female',
    cnic: '35201-1122334-3',
    maritalStatus: 'Single',
    currentAddress: '77 Chapel Street, Salford, M3 5DN',
    employeeId: 'CCE008',
    jobTitle: 'Admin Assistant',
    department: 'Admin',
    employmentType: 'part_time',
    status: 'active',
    startDate: '2024-02-12',
    workLocation: 'Head Office',
    manager: 'Sarah Thompson',
    salary: 14000,
    emergencyContactName: 'Bilal Siddiqui',
    emergencyContactPhone: '+44 7700 900093',
    emergencyContactRelation: 'Parent',
    bankName: 'NatWest',
    accountNumber: 'GB29NWBK20000000000007',
    skills: 'Data Entry, Filing, Microsoft Office, Scheduling',
  },
  {
    name: 'Mohammed Al-Hassan',
    email: 'm.alhassan@cabcallexperts.com',
    phone: '+44 7700 900009',
    dob: '1983-01-25',
    gender: 'Male',
    maritalStatus: 'Married',
    currentAddress: '11 King Street, Manchester, M2 6AW',
    employeeId: 'CCE009',
    jobTitle: 'General Manager',
    department: 'Management',
    employmentType: 'full_time',
    status: 'active',
    startDate: '2017-07-01',
    workLocation: 'Head Office',
    manager: 'CEO',
    salary: 58000,
    bankName: 'HSBC',
    accountNumber: 'GB29HSBC20000000000008',
    taxNumber: '44556677',
    skills: 'Business Operations, P&L Management, Stakeholder Relations, Strategy',
    notes: 'Reports directly to CEO. Oversees all departments.',
  },
  {
    name: 'Chloe Davies',
    email: 'chloe.davies@cabcallexperts.com',
    phone: '+44 7700 900010',
    dob: '1999-04-11',
    gender: 'Female',
    maritalStatus: 'Single',
    currentAddress: '66 Mosley Street, Manchester, M2 3HZ',
    employeeId: 'CCE010',
    jobTitle: 'Customer Service Agent',
    department: 'Customer Service',
    employmentType: 'contract',
    status: 'active',
    startDate: '2025-09-01',
    workLocation: 'Remote',
    manager: 'Priya Sharma',
    salary: 21000,
    emergencyContactName: 'Tom Davies',
    emergencyContactPhone: '+44 7700 900092',
    emergencyContactRelation: 'Parent',
    bankName: 'Monzo',
    accountNumber: 'GB29MONZ20000000000009',
    skills: 'Live Chat, Email Support, CRM Systems',
    notes: '6-month contract, review in August 2026.',
  },
  {
    name: 'Tariq Butt',
    email: 'tariq.butt@cabcallexperts.com',
    phone: '+44 7700 900011',
    dob: '1992-06-09',
    gender: 'Male',
    cnic: '35202-5544332-4',
    maritalStatus: 'Married',
    currentAddress: '4 Rochdale Road, Manchester, M4 4HQ',
    employeeId: 'CCE011',
    jobTitle: 'Night Shift Dispatcher',
    department: 'Dispatch',
    employmentType: 'full_time',
    status: 'suspended',
    startDate: '2022-10-05',
    workLocation: 'Head Office',
    manager: 'Ahmed Raza',
    salary: 27000,
    bankName: 'Barclays',
    accountNumber: 'GB29BARC20000000000010',
    skills: 'Dispatch, Night Operations, Incident Reporting',
    notes: 'Suspended pending disciplinary review (2026-04-10).',
  },
  {
    name: 'Emma Wilson',
    email: 'emma.wilson@cabcallexperts.com',
    phone: '+44 7700 900012',
    dob: '1987-10-03',
    gender: 'Female',
    maritalStatus: 'Married',
    currentAddress: '30 Wilmslow Road, Manchester, M14 5TQ',
    employeeId: 'CCE012',
    jobTitle: 'Payroll Officer',
    department: 'Admin',
    employmentType: 'full_time',
    status: 'active',
    startDate: '2020-01-06',
    workLocation: 'Head Office',
    manager: 'Sarah Thompson',
    salary: 32000,
    bankName: 'Halifax',
    accountNumber: 'GB29HLFX20000000000011',
    taxNumber: '33221100',
    skills: 'Payroll Processing, HMRC Submissions, Sage, Excel',
    notes: 'Handles full payroll for all 50+ staff.',
  },
]

export async function seedEmployees(): Promise<{ added: number; skipped: boolean }> {
  // Check if data already exists
  const existing = await getDocs(query(collection(db, 'employees')))
  if (!existing.empty) {
    return { added: 0, skipped: true }
  }

  const col = collection(db, 'employees')
  let added = 0
  for (const emp of DUMMY_EMPLOYEES) {
    await addDoc(col, {
      ...emp,
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    })
    added++
  }
  return { added, skipped: false }
}
