import { collection, addDoc, serverTimestamp, getDocs, query } from 'firebase/firestore'
import { db } from '../config/firebase'
import type { FirebaseEmployee } from '../hooks/useFirebaseEmployees'

const DUMMY_EMPLOYEES: Omit<FirebaseEmployee, 'id'>[] = [
  {
    employeeId: 'CCE001', name: 'Ahmed Raza',
    email: 'ahmed.raza@cabcallexperts.com', phone: '03001234001',
    dob: '1990-03-15', gender: 'Male', cnic: '35202-1234567-1',
    maritalStatus: 'Married', religion: 'Islam',
    currentAddress: 'H# 12, Satellite Town, Rawalpindi',
    permanentAddress: 'H# 12, Satellite Town, Rawalpindi',
    currentCity: 'Rawalpindi', hometown: 'Rawalpindi',
    jobTitle: 'Operations Manager', department: 'Operations',
    employmentType: 'full_time', status: 'active', startDate: '2021-01-10',
    companyName: 'CabCall Experts',
    emergencyContactName: 'Fatima Raza', emergencyContactPhone: '03001234099',
    emergencyContactRelation: 'Spouse', emergencyContactType: 'Mobile',
    accountNumber: '02480000000001',
  },
  {
    employeeId: 'CCE002', name: 'Sarah Khan',
    email: 'sarah.khan@cabcallexperts.com', phone: '03001234002',
    dob: '1985-07-22', gender: 'Female', maritalStatus: 'Single',
    religion: 'Islam',
    currentAddress: 'H# 45, F-7, Islamabad',
    currentCity: 'Islamabad', hometown: 'Islamabad',
    jobTitle: 'HR Manager', department: 'HR',
    employmentType: 'full_time', status: 'active', startDate: '2019-06-01',
    companyName: 'CabCall Experts',
    emergencyContactName: 'Bilal Khan', emergencyContactPhone: '03001234098',
    emergencyContactRelation: 'Brother', emergencyContactType: 'Mobile',
    accountNumber: '02480000000002',
  },
  {
    employeeId: 'CCE003', name: 'Usman Ali',
    email: 'usman.ali@cabcallexperts.com', phone: '03001234003',
    dob: '1994-11-05', gender: 'Male', cnic: '35201-9876543-1',
    maritalStatus: 'Single', religion: 'Islam',
    currentAddress: 'H# 8, G-9, Islamabad',
    currentCity: 'Islamabad', hometown: 'Lahore',
    jobTitle: 'Dispatch Coordinator', department: 'Dispatch',
    employmentType: 'full_time', status: 'active', startDate: '2022-03-14',
    companyName: 'CabCall Experts',
    emergencyContactName: 'Ali Khan', emergencyContactPhone: '03001234097',
    emergencyContactRelation: 'Father', emergencyContactType: 'Mobile',
    accountNumber: '02480000000003',
  },
  {
    employeeId: 'CCE004', name: 'Zara Malik',
    email: 'zara.malik@cabcallexperts.com', phone: '03001234004',
    dob: '1997-02-28', gender: 'Female', cnic: '35202-7654321-2',
    maritalStatus: 'Single', religion: 'Islam',
    currentAddress: 'H# 22, I-8, Islamabad',
    currentCity: 'Islamabad', hometown: 'Faisalabad',
    jobTitle: 'Customer Service Agent', department: 'Customer Service',
    employmentType: 'full_time', status: 'active', startDate: '2023-01-09',
    companyName: 'CabCall Experts',
    emergencyContactName: 'Hina Malik', emergencyContactPhone: '03001234096',
    emergencyContactRelation: 'Sister', emergencyContactType: 'Mobile',
    accountNumber: '02480000000004',
  },
  {
    employeeId: 'CCE005', name: 'Kamran Sheikh',
    email: 'kamran.sheikh@cabcallexperts.com', phone: '03001234005',
    dob: '1991-09-14', gender: 'Male',
    maritalStatus: 'Married', religion: 'Islam',
    currentAddress: 'H# 5, E-11, Islamabad',
    currentCity: 'Islamabad', hometown: 'Karachi',
    jobTitle: 'IT Administrator', department: 'IT',
    employmentType: 'full_time', status: 'active', startDate: '2020-08-17',
    companyName: 'CabCall Experts',
    emergencyContactName: 'Sana Sheikh', emergencyContactPhone: '03001234095',
    emergencyContactRelation: 'Spouse', emergencyContactType: 'Mobile',
    accountNumber: '02480000000005',
  },
  {
    employeeId: 'CCE006', name: 'Priya Noor',
    email: 'priya.noor@cabcallexperts.com', phone: '03001234006',
    dob: '1993-05-30', gender: 'Female',
    maritalStatus: 'Single', religion: 'Islam',
    currentAddress: 'H# 19, G-10, Islamabad',
    currentCity: 'Islamabad', hometown: 'Multan',
    jobTitle: 'Customer Service Team Lead', department: 'Customer Service',
    employmentType: 'full_time', status: 'on_leave', startDate: '2021-11-22',
    companyName: 'CabCall Experts',
    emergencyContactName: 'Raj Noor', emergencyContactPhone: '03001234094',
    emergencyContactRelation: 'Father', emergencyContactType: 'Mobile',
    accountNumber: '02480000000006',
  },
  {
    employeeId: 'CCE007', name: 'James Tariq',
    email: 'james.tariq@cabcallexperts.com', phone: '03001234007',
    dob: '1988-12-01', gender: 'Male',
    maritalStatus: 'Divorced', religion: 'Islam',
    currentAddress: 'H# 3, F-8, Islamabad',
    currentCity: 'Islamabad', hometown: 'Peshawar',
    jobTitle: 'Senior Dispatcher', department: 'Dispatch',
    employmentType: 'full_time', status: 'active', startDate: '2018-04-03',
    companyName: 'CabCall Experts',
    accountNumber: '02480000000007',
  },
  {
    employeeId: 'CCE008', name: 'Aisha Siddiqui',
    email: 'aisha.siddiqui@cabcallexperts.com', phone: '03001234008',
    dob: '1996-08-18', gender: 'Female', cnic: '35201-1122334-3',
    maritalStatus: 'Single', religion: 'Islam',
    currentAddress: 'H# 77, G-11, Islamabad',
    currentCity: 'Islamabad', hometown: 'Quetta',
    jobTitle: 'Admin Assistant', department: 'Admin',
    employmentType: 'part_time', status: 'active', startDate: '2024-02-12',
    companyName: 'CabCall Experts',
    emergencyContactName: 'Bilal Siddiqui', emergencyContactPhone: '03001234093',
    emergencyContactRelation: 'Father', emergencyContactType: 'Mobile',
    accountNumber: '02480000000008',
  },
  {
    employeeId: 'CCE009', name: 'Omar Hassan',
    email: 'omar.hassan@cabcallexperts.com', phone: '03001234009',
    dob: '1983-01-25', gender: 'Male',
    maritalStatus: 'Married', religion: 'Islam',
    currentAddress: 'H# 11, F-6, Islamabad',
    currentCity: 'Islamabad', hometown: 'Islamabad',
    jobTitle: 'General Manager', department: 'Management',
    employmentType: 'full_time', status: 'active', startDate: '2017-07-01',
    companyName: 'CabCall Experts',
    accountNumber: '02480000000009',
  },
  {
    employeeId: 'CCE010', name: 'Chloe Ahmed',
    email: 'chloe.ahmed@cabcallexperts.com', phone: '03001234010',
    dob: '1999-04-11', gender: 'Female',
    maritalStatus: 'Single', religion: 'Islam',
    currentAddress: 'H# 66, I-10, Islamabad',
    currentCity: 'Islamabad', hometown: 'Rawalpindi',
    jobTitle: 'Customer Service Agent', department: 'Customer Service',
    employmentType: 'contract', status: 'active', startDate: '2025-09-01',
    companyName: 'CabCall Experts',
    emergencyContactName: 'Tom Ahmed', emergencyContactPhone: '03001234092',
    emergencyContactRelation: 'Father', emergencyContactType: 'Mobile',
    accountNumber: '02480000000010',
  },
  {
    employeeId: 'CCE011', name: 'Tariq Butt',
    email: 'tariq.butt@cabcallexperts.com', phone: '03001234011',
    dob: '1992-06-09', gender: 'Male', cnic: '35202-5544332-4',
    maritalStatus: 'Married', religion: 'Islam',
    currentAddress: 'H# 4, G-8, Islamabad',
    currentCity: 'Islamabad', hometown: 'Lahore',
    jobTitle: 'Night Shift Dispatcher', department: 'Dispatch',
    employmentType: 'full_time', status: 'suspended', startDate: '2022-10-05',
    companyName: 'CabCall Experts',
    accountNumber: '02480000000011',
  },
  {
    employeeId: 'CCE012', name: 'Emma Wilson',
    email: 'emma.wilson@cabcallexperts.com', phone: '03001234012',
    dob: '1987-10-03', gender: 'Female',
    maritalStatus: 'Married', religion: 'Islam',
    currentAddress: 'H# 30, F-11, Islamabad',
    currentCity: 'Islamabad', hometown: 'Islamabad',
    jobTitle: 'Payroll Officer', department: 'Finance',
    employmentType: 'full_time', status: 'active', startDate: '2020-01-06',
    companyName: 'CabCall Experts',
    accountNumber: '02480000000012',
  },
]

export async function seedEmployees(): Promise<{ added: number; skipped: boolean }> {
  const existing = await getDocs(query(collection(db, 'employees')))
  if (!existing.empty) return { added: 0, skipped: true }

  const col = collection(db, 'employees')
  let added = 0
  for (const emp of DUMMY_EMPLOYEES) {
    await addDoc(col, { ...emp, createdAt: serverTimestamp(), updatedAt: serverTimestamp() })
    added++
  }
  return { added, skipped: false }
}
